# Site settings
title: "Marko Morrison"
bye_message: "o/"
baseurl: ""
url: "https://peacock4o.github.io/"
disqus: peacock4o

# Header settings
nick: "peacock4o"
mail:
    fs: "andrew"
    domain: "cmu"
    ext: "edu"
source_code:
    server: "github.com"
    nick: "peacock4o"
blog:
    server: "peacock4o.github.io"
    nick: "peacock4o"
fingerprint_key: "58829B20BB59BDF8F2E0331E23AC1C8074BF029D"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
